// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpfRF6vvaWbZt5NUKgJJ9wa8z5xGuZl-s',
    appId: '1:145551522874:web:8c4d4c544e72ed6e48c903',
    messagingSenderId: '145551522874',
    projectId: 'eos-advance',
    authDomain: 'eos-advance.firebaseapp.com',
    storageBucket: 'eos-advance.firebasestorage.app',
    measurementId: 'G-YYTYYTRRZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7BgB5ix2bqQeZz4M5ajvB8ej0YgEmuHM',
    appId: '1:145551522874:android:11752679284c73c548c903',
    messagingSenderId: '145551522874',
    projectId: 'eos-advance',
    storageBucket: 'eos-advance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGVW8aSjlNUMF6mFQfLdPwNMjox6ZN6F4',
    appId: '1:145551522874:ios:6a7e93430ae75a4b48c903',
    messagingSenderId: '145551522874',
    projectId: 'eos-advance',
    storageBucket: 'eos-advance.firebasestorage.app',
    iosBundleId: 'com.example.eosAdvanceLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGVW8aSjlNUMF6mFQfLdPwNMjox6ZN6F4',
    appId: '1:145551522874:ios:6a7e93430ae75a4b48c903',
    messagingSenderId: '145551522874',
    projectId: 'eos-advance',
    storageBucket: 'eos-advance.firebasestorage.app',
    iosBundleId: 'com.example.eosAdvanceLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpfRF6vvaWbZt5NUKgJJ9wa8z5xGuZl-s',
    appId: '1:145551522874:web:83ce5f985015b03648c903',
    messagingSenderId: '145551522874',
    projectId: 'eos-advance',
    authDomain: 'eos-advance.firebaseapp.com',
    storageBucket: 'eos-advance.firebasestorage.app',
    measurementId: 'G-E6L4VJ2WP7',
  );
}
